package engine;

public enum InputType {
	
	KEY_PRESSED,
	KEY_RELEASED,
	KEY_TYPED,
	WINDOW_ACTIVATED,
	WINDOW_DEACTIVATED,
	WINDOW_CLOSED,
	WINDOW_CLOSING,
	WINDOW_DEICONIFIED,
	WINDOW_ICONIFIED,
	WINDOW_OPENED,
	MOUSE_WHEEL_MOVED,
	MOUSE_CLICKED,
	MOUSE_ENTERED,
	MOUSE_EXITED,
	MOUSE_PRESSED,
	MOUSE_RELEASED,
	MOUSE_DRAGGED,
	MOUSE_MOVED,
	MOUSE_DOUBLE_CLICKED;

}
